### ISSUE TITLE
ModuleNotFoundError: No module named 'PuzzleLib.Cuda'

### ISSUE THREAD

**Issue by dmzubr** [sovaai/sova-asr#9]
Приветствую!

Не удаётся запустить Docker контейнер для выполнения дообучения.

Сначала пробовал напрямую по ридми.
[(docker build log)](https://www.dropbox.com/s/qrosm7r5tb4njc2/sova_asr_docker_build.log?dl=1)
В результате:
`ModuleNotFoundError: No module named 'PuzzleLib.Cuda'`

Потом сделал билд контейнера вручную (docker build --no-cache) и далее внутри контейнера при выполнении команды
_python3 Train.py_
получил аналогичный результат.

Далее попробовал внутри контейнера собрать PuzzleLib из сырцов.
В результате получил
`root@8f3668178d66:/tmp/PuzzleLib# python3 setup.py install --backend=cuda
running install
backends chosen: ['cuda']
converters chosen: []
Traceback (most recent call last):
  File "setup.py", line 470, in <module>
    main()
  File "setup.py", line 465, in main
    keywords=["puzzlelib", "deep learning", "neural nets"]
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 119, in run
    self.distribution.package_data = self.installPackages(self.projectPath, self.cachePath, handlers, options)
  File "setup.py", line 148, in installPackages
    packageData.update(handler(pkgSrc, pkgDst, options))
  File "setup.py", line 192, in installGpuPackages
    from PuzzleLib.Cuda.CheckInstall import checkCudaInstall
ModuleNotFoundError: No module named 'PuzzleLib.Cuda'`

Далее попробовал откатить исходник  на предыдущий коммит (_git checkout bd591152fe769fe76f9d3b38aa620a7b0ce91e3f_).
В результате - то же, что при попытке предыдущего вызова setup.py:
`ModuleNotFoundError: No module named 'PuzzleLib.Cuda'`

**Comment by sxdxfan** [comment]
@dmzubr, добрый день! Да, вижу, в чём проблема, сначала происходит установка PuzzleLib из requirements.txt, что работает для CPU версии, а затем при попытке переустановить PuzzleLib с бэкендом CUDA pip проходит дальше, считая, что PuzzleLib уже установлен (но он установлен без CUDA бэкенда). Пофиксим с новым релизом, пока попробуйте убрать из requirements.txt PuzzleLib:
https://github.com/sovaai/sova-asr/blob/8a19b16013df4f3b15b2e439b3bed1d8174818eb/requirements.txt#L8
и дальше перебилдить образ для обучения, установится корректная версия из Dockerfile.

**Comment by dmzubr** [comment]
> @dmzubr, добрый день! Да, вижу, в чём проблема, сначала происходит установка PuzzleLib из requirements.txt, что работает для CPU версии, а затем при попытке переустановить PuzzleLib с бэкендом CUDA pip проходит дальше, считая, что PuzzleLib уже установлен (но он установлен без CUDA бэкенда). Пофиксим с новым релизом, пока попробуйте убрать из requirements.txt PuzzleLib:
> https://github.com/sovaai/sova-asr/blob/8a19b16013df4f3b15b2e439b3bed1d8174818eb/requirements.txt#L8
> 
> 
> и дальше перебилдить образ для обучения, установится корректная версия из Dockerfile.

Спасибо!

Помогло, запустил дообучение.

Отпишусь потом по метрикам - что с результатами.

**Comment by cyberblastru** [comment]
Добрый день.
Установил последний докер. У меня только CPU. Сделал по инструкции: поменял в докерфайле строчки, в докер-композе убрал секции, в config.ini  cpu=0. Всё равно вылетает ошибка

[2022-10-28 04:07:36 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/sova-asr/app.py", line 2, in <module>
    from file_handler import FileHandler
  File "/sova-asr/file_handler.py", line 7, in <module>
    from punctuator import Punctuator
  File "/sova-asr/punctuator.py", line 4, in <module>
    from bert_punctuator.bert import BertPunc, BertConfig
  File "/sova-asr/bert_punctuator/bert.py", line 5, in <module>
    from bert_punctuator.modules import Embedder, Linear
  File "/sova-asr/bert_punctuator/modules.py", line 4, in <module>
    from PuzzleLib.Backend import gpuarray, Blas
  File "/usr/local/lib/python3.6/dist-packages/PuzzleLib/Backend/gpuarray.py", line 201, in <module>
    autoinit()
  File "/usr/local/lib/python3.6/dist-packages/PuzzleLib/Backend/gpuarray.py", line 40, in autoinit
    initCuda()
  File "/usr/local/lib/python3.6/dist-packages/PuzzleLib/Backend/gpuarray.py", line 50, in initCuda
    from PuzzleLib.Cuda import Backend, Utils
ModuleNotFoundError: No module named 'PuzzleLib.Cuda'
